NAME	= libgnl.a
CC		= cc
CFLAGS	= -Wall -Wextra -Werror
LIBFT_DIR = ../libft

SRCS	= get_next_line.c get_next_line_utils.c
OBJS	= $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -I$(LIBFT_DIR) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
